---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: torbencarstens/regular-dicers-backend{{TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_URL: "{{DATABASE_URL}}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ROCKET_ENV: "prod"
