-- Your SQL goes here
BEGIN TRANSACTION;
    INSERT INTO ingredients (id, name) VALUES (0, 'Captain Morgan Spiced Gold');
    INSERT INTO ingredients (id, name) VALUES (1, 'Myer''s Rum');
    INSERT INTO ingredients (id, name) VALUES (2, 'Red Bull');
    INSERT INTO ingredients (id, name) VALUES (3, 'Erdbeermus');
    INSERT INTO ingredients (id, name) VALUES (4, 'Lemon');
    INSERT INTO ingredients (id, name) VALUES (5, 'Licor 43');
    INSERT INTO ingredients (id, name) VALUES (6, 'Apricot Brandy');
    INSERT INTO ingredients (id, name) VALUES (7, 'Bananen-Sirup');
    INSERT INTO ingredients (id, name) VALUES (8, 'Zucker-Sirup');
    INSERT INTO ingredients (id, name) VALUES (9, 'Maracuja');
    INSERT INTO ingredients (id, name) VALUES (10, 'Zitrone');
    INSERT INTO ingredients (id, name) VALUES (11, 'Paloma Pink Grapefruit Limonade');
    INSERT INTO ingredients (id, name) VALUES (12, 'Vodka');
    INSERT INTO ingredients (id, name) VALUES (13, 'De Kuyper Blue Curacao');
    INSERT INTO ingredients (id, name) VALUES (14, 'Peachtree');
    INSERT INTO ingredients (id, name) VALUES (15, 'Malibu');
    INSERT INTO ingredients (id, name) VALUES (16, '7UP');
    INSERT INTO ingredients (id, name) VALUES (17, 'Rum');
    INSERT INTO ingredients (id, name) VALUES (18, 'Kirsche');
    INSERT INTO ingredients (id, name) VALUES (19, 'Pfirsich');
    INSERT INTO ingredients (id, name) VALUES (20, 'Cola');
    INSERT INTO ingredients (id, name) VALUES (21, 'Waldbeeren-Sirup');
    INSERT INTO ingredients (id, name) VALUES (22, 'Weisser Zucker');
    INSERT INTO ingredients (id, name) VALUES (23, 'Orange');
    INSERT INTO ingredients (id, name) VALUES (24, 'Pampero Especial');
    INSERT INTO ingredients (id, name) VALUES (25, 'Soda');
    INSERT INTO ingredients (id, name) VALUES (26, 'Kokosnuss-Sirup');
    INSERT INTO ingredients (id, name) VALUES (27, 'Tequila');
    INSERT INTO ingredients (id, name) VALUES (28, 'Zerstossenes Eis');
    INSERT INTO ingredients (id, name) VALUES (29, 'Sahne');
    INSERT INTO ingredients (id, name) VALUES (30, 'Puderzucker');
    INSERT INTO ingredients (id, name) VALUES (31, 'De Kuyper Grenadine');
    INSERT INTO ingredients (id, name) VALUES (32, 'Amaretto Disaronno');
    INSERT INTO ingredients (id, name) VALUES (33, 'Ananas');
    INSERT INTO ingredients (id, name) VALUES (34, 'Apfel');
    INSERT INTO ingredients (id, name) VALUES (35, 'Limetten');
    INSERT INTO ingredients (id, name) VALUES (36, 'Cachace');
    INSERT INTO ingredients (id, name) VALUES (37, 'Minze');
    INSERT INTO ingredients (id, name) VALUES (38, 'Midori');
    INSERT INTO ingredients (id, name) VALUES (39, 'Gin');
    INSERT INTO ingredients (id, name) VALUES (40, 'Triple Sec');
    INSERT INTO ingredients (id, name) VALUES (41, 'Cherry Brandy');
    INSERT INTO ingredients (id, name) VALUES (42, 'Mandel-Sirup');
    INSERT INTO ingredients (id, name) VALUES (43, 'Sierra Tequila Silver');
    INSERT INTO ingredients (id, name) VALUES (44, 'Erdbeeren');
    INSERT INTO ingredients (id, name) VALUES (45, 'Schwarze Johannisbeere');
    INSERT INTO ingredients (id, name) VALUES (46, 'Old Pascas 73%');
    INSERT INTO ingredients (id, name) VALUES (47, 'Pampero Blanco');
    INSERT INTO ingredients (id, name) VALUES (48, 'Cranberry');
    INSERT INTO ingredients (id, name) VALUES (49, 'Ginger Ale');
    INSERT INTO ingredients (id, name) VALUES (50, 'Lime');
    INSERT INTO ingredients (id, name) VALUES (51, 'Aperol');
    INSERT INTO ingredients (id, name) VALUES (52, 'Wray & Nephew');
    INSERT INTO ingredients (id, name) VALUES (53, 'Mango-Sirup');
END;
