name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install postgres dependencies
        run: sudo apt-get install -y libpq-dev
      - name: Install nightly
        run: rustup update nightly
      - name: Build
        run: cargo +nightly build --verbose
      - name: Actions for Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The build has failed'
        if: failure()
